spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ifx_java_spring_starter
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect